all:
  children:
    masters:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: david

#    switches:
#      hosts:
#    rans:
#      hosts:
#        10.64.45.22:
#          xx-name: bp2
